//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сompany
    {
        public int CompanyId { get; set; }
        public string Name { get; set; }
        public Nullable<long> INN { get; set; }
        public Nullable<long> MailIndex { get; set; }
        public string Address { get; set; }
        public bool IsDeleted { get; set; }
    }
}
